feat:Update to Kochava 4.2.1
mparticle-integrations/mparticle-android-integration-kochava pull request #41
Opened 2023-02-09 18:20 UTC by BrandonStalnaker

## Summary
 - Updated to Kochava 4.2.1

 ## Testing Plan
 - Tested locally 

 ## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
 - Closes https://go.mparticle.com/work/SQDSDKS-4963

2023-02-22 17:04 UTC, markvdouw requested changes
Shouldn't we add some test about the new changes?

2023-02-22 17:04 UTC, markvdouw commented on src/main/kotlin/com/mparticle/kits/KochavaKit.kt
> +            Tracker.getInstance().startWithAppGuid(context.applicationContext, it)
This returns a configuration? Based on the name of the function "startWithAppGuid" doesnt seems to..
If it doesn't.. line 34 wont be true and none of the code will be triggered.

2023-02-22 17:04 UTC, markvdouw commented on src/main/kotlin/com/mparticle/kits/KochavaKit.kt
> +    override fun setInstallReferrer(intent: Intent) {}
Should we propagate to the ReferralReceiver?

2023-02-22 17:04 UTC, markvdouw commented on src/main/kotlin/com/mparticle/kits/KochavaKit.kt
>          if (identityType == IdentityType.CustomerId) {
Shouldn't all this be simplified? Lines 77 and 81 are exactly the same

2023-02-23 14:42 UTC, BrandonStalnaker commented on src/main/kotlin/com/mparticle/kits/KochavaKit.kt
> +            Tracker.getInstance().startWithAppGuid(context.applicationContext, it)
configuration is being set by 'getSettings()[APP_ID]?.let' here right. Maybe let works way differently here than it does in Swift?

2023-02-23 15:05 UTC, BrandonStalnaker commented on src/main/kotlin/com/mparticle/kits/KochavaKit.kt
> +    override fun setInstallReferrer(intent: Intent) {}
In their new sdk I couldn't find anything comparable to ReferralReceiver or any way ingest intent. I believe the functionality has been removed but let me know if you see different https://support.kochava.com/sdk-integration/android-sdk-integration/android-using-the-sdk/

2023-02-23 16:22 UTC, markvdouw commented on src/main/kotlin/com/mparticle/kits/KochavaKit.kt
> +            Tracker.getInstance().startWithAppGuid(context.applicationContext, it)
I was just saying that the result of the let block is being assigned to the immutable configuration variable. So my question was what is being assigned? Does "startWithAppGuid" returns a configuration?

2023-02-23 16:44 UTC, BrandonStalnaker commented on src/main/kotlin/com/mparticle/kits/KochavaKit.kt
> +            Tracker.getInstance().startWithAppGuid(context.applicationContext, it)
Gotcha, I didn't realize the block assigned to the original value. Fixed

2023-02-23 16:55 UTC, markvdouw approved these changes
LGTM

2023-02-23 16:59 UTC, merged